'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace TwoDetailGrids


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' grid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected grid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' masterDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected masterDataSource As System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' productsDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected productsDataSource As System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' orderItemsDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected orderItemsDataSource As System.Web.UI.WebControls.AccessDataSource
	End Class
End Namespace
